"""add job_description to application

Revision ID: 2b8a16362ee5
Revises: d2b908dec8c6
Create Date: 2026-03-28 04:35:19.651468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8a16362ee5'
down_revision = 'd2b908dec8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.Enum('SKILLS', 'FIT_SUMMARY', 'INTERVIEW', name='analysistype', native_enum=False), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'analysis_type', name='uq_analysis_app_type')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('job_description')

    op.drop_table('ai_analysis')
    # ### end Alembic commands ###
