"""initial schema

Revision ID: d2b908dec8c6
Revises: 
Create Date: 2026-03-28 01:47:46.437427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b908dec8c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('role_title', sa.String(length=200), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=False),
    sa.Column('current_status', sa.Enum('APPLIED', 'PHONE_SCREEN', 'TECHNICAL', 'FINAL_ROUND', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('LINKEDIN', 'REFERRAL', 'COLD_OUTREACH', 'COMPANY_WEBSITE', 'JOB_BOARD', 'OTHER', name='applicationsource', native_enum=False), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('company_size', sa.Enum('STARTUP', 'MID_SIZE', 'ENTERPRISE', name='companysize', native_enum=False), nullable=False),
    sa.Column('company_type', sa.Enum('PUBLIC', 'PRIVATE', 'NONPROFIT', 'UNKNOWN', name='companytype', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('APPLIED', 'PHONE_SCREEN', 'TECHNICAL', 'FINAL_ROUND', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'PASSED', 'FAILED', 'WITHDREW', name='stageoutcome', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_event')
    op.drop_table('application')
    # ### end Alembic commands ###
